# This is not a workspace because I don't want to have to
# upload my own `tokio-stream-multiplexor` fork to crates.io.
# Note that we need to delete lib/tokio-stream-multiplexor/Cargo.toml
# before publishing.

[package]
name = "rusty-penguin"
version = "0.3.1"
authors = ["Zhang Maiyun <me@myzhangll.xyz>"]
edition = "2021"
description = "A fast TCP/UDP tunnel, transported over HTTP WebSockets"
readme = "README.md"
repository = "https://github.com/myzhang1029/penguin-rs"
license = "Apache-2.0 OR GPL-3.0-or-later"
keywords = ["cli", "web", "websocket"]
categories = ["asynchronous", "command-line-utilities", "network-programming"]

[[bin]]
name = "penguin"
path = "src/main.rs"

[lib]
name = "penguin_tokio_stream_multiplexor"
path = "lib/tokio-stream-multiplexor/src/lib.rs"

[dependencies]
clap = { version = "4", features = ["cargo", "derive"] }
futures-util = { version = "0.3", default-features = false }
http = "0.2"
rustls = "0.20"
rustls-native-certs = { version = "0.6", optional = true }
rustls-pemfile = "1"
thiserror = "1"
tokio = { version = "1", features = ["io-std", "macros", "rt-multi-thread"] }
tokio-tungstenite = "0.18"
tracing = "0.1"
tracing-subscriber = "0.3"
tungstenite = "0.18"
url = "2"
warp-reverse-proxy = { version = "1", features = ["rustls-tls"], default-features = false }
warp = { version = "0.3", features = ["tls"] }
webpki = "0.22"
webpki-roots = { version = "0.22", optional = true }

# From tokio-stream-multiplexor
async-channel = "1"
bincode = "1"
bytes = { version = "1", features = ["serde"] }
futures = "0.3"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
tokio-util = { version = "0.7", features = ["codec"] }

[dev-dependencies]
tempfile = "3"
rcgen = "0.10"

# From tokio-stream-multiplexor
criterion = { version = "0.3", features = ["async_tokio"] }
ctor = "0.1"
tokio = { version = "1", features = ["io-util", "io-std", "rt", "net", "macros", "time", "rt-multi-thread"] }

[features]
default = ["rustls-native-roots"]
# Note that it does not make sense to use rustls-webpki-roots and
# rustls-native-roots at the same time, but there must be at least one. 
rustls-webpki-roots = ["webpki-roots", "tokio-tungstenite/rustls-tls-webpki-roots", "tungstenite/rustls-tls-webpki-roots"]
rustls-native-roots = ["rustls-native-certs", "tokio-tungstenite/rustls-tls-native-roots", "tungstenite/rustls-tls-native-roots"]

[profile.release]
debug = true
