[package]
name = "penguin-rs"
version = "0.1.0"
authors = ["Zhang Maiyun <me@myzhangll.xyz>"]
edition = "2021"
description = "A fast TCP/UDP tunnel, transported over HTTP WebSockets"
readme = "README.md"
repository = "https://github.com/myzhang1029/penguin-rs"
license = "Apache-2.0 OR GPL-3.0-or-later"
keywords = ["cli"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["cargo", "derive"] }
env_logger = "0.10"
futures-util = { version = "0.3", default-features = false }
log = "0.4"
warp-reverse-proxy = { version = "1", features = ["rustls-tls"], default-features = false }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
warp = { version = "0.3", features = ["tls"] }