[package]
name = "penguin"
version = "0.1.0"
authors = ["Zhang Maiyun <me@myzhangll.xyz>"]
edition = "2021"
description = "A fast TCP/UDP tunnel, transported over HTTP WebSockets"
readme = "README.md"
repository = "https://github.com/myzhang1029/penguin-rs"
license = "Apache-2.0 OR GPL-3.0-or-later"
keywords = ["cli", "web", "websocket"]
categories = ["asynchronous", "command-line-utilities", "network-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-socks5 = "0.5"
clap = { version = "4", features = ["cargo", "derive"] }
env_logger = "0.10"
futures-channel = "0.3"
futures-util = { version = "0.3", default-features = false }
http = "0.2"
log = "0.4"
rustls = "0.20"
rustls-native-certs = { version = "0.6", optional = true }
rustls-pemfile = "1"
thiserror = "1"
tokio = { version = "1", features = ["io-std", "macros", "rt-multi-thread"] }
tokio-stream-multiplexor = "0.5"
tokio-tungstenite = "0.18"
tungstenite = "0.18"
url = "2"
warp-reverse-proxy = { version = "1", features = ["rustls-tls"], default-features = false }
warp = { version = "0.3", features = ["tls"] }
webpki = "0.22"
webpki-roots = { version = "0.22", optional = true }

[dev-dependencies]
tempfile = "3"
rcgen = "0.10"

[features]
default = ["rustls-native-roots"]
# Note that it does not make sense to use rustls-webpki-roots and
# rustls-native-roots at the same time, but there must be at least one. 
rustls-webpki-roots = ["webpki-roots", "tokio-tungstenite/rustls-tls-webpki-roots", "tungstenite/rustls-tls-webpki-roots"]
rustls-native-roots = ["rustls-native-certs", "tokio-tungstenite/rustls-tls-native-roots", "tungstenite/rustls-tls-native-roots"]
