[package]
name = "rusty-penguin"
version = "0.5.2"
authors = ["Zhang Maiyun <me@myzhangll.xyz>"]
edition = "2021"
description = "A fast TCP/UDP tunnel, transported over HTTP WebSocket"
readme = "README.md"
repository = "https://github.com/myzhang1029/penguin-rs"
license = "Apache-2.0 OR GPL-3.0-or-later"
keywords = ["cli", "web", "websocket"]
categories = ["asynchronous", "command-line-utilities", "network-programming"]

[[bin]]
name = "penguin"
path = "src/main.rs"
required-features = ["penguin-binary"]

[lib]
name = "penguin_mux"
path = "src/mux/lib.rs"

[dependencies]
arc-swap = { version = "1", optional = true }
base64 = { version = "0.21", optional = true }
bytes = "1"
clap = { version = "4", features = ["cargo", "derive"], optional = true }
console-subscriber = { version = "0.1", optional = true }
futures-util = { version = "0.3", default-features = false }
http = "0.2"
hyper = { version = ">=0.14.10", features = ["client", "server", "http1", "http2"], optional = true }
hyper-rustls = { version = "0.24", features = ["http1", "http2"], optional = true }
hyper-tls = { version = "0.5", optional = true }
native-tls = { version = "0.2", optional = true }
once_cell = { version = "1", optional = true }
parking_lot = "0.12"
rand = "0.8"
rustls = { version = "0.21", optional = true, features = ["dangerous_configuration"] }
rustls-native-certs = { version = "0.6", optional = true }
rustls-pemfile = { version = "1", optional = true }
sha1 = { version = "0.10", optional = true }
thiserror = "1"
tokio = { version = ">=1.23.1", features = ["macros", "parking_lot", "rt", "sync", "time"] }
tokio-native-tls = { version = "0.3", optional = true }
tokio-rustls = { version = "0.24", optional = true }
tokio-tungstenite = { version = ">=0.20.1", default-features = false }
#tokio-tungstenite = { git = "https://github.com/snapview/tokio-tungstenite.git", rev="f4dcfec257b06a3dbab43df9b2efa7c2b7c8a6db", default-features = false }
#tokio-tungstenite = { version = "0.19", default-features = false }
tracing = "0.1"
tracing-subscriber = { version = "0.3", optional = true }
webpki-roots = { version = "0.25", optional = true }

[dev-dependencies]
ctor = "0.2"
tempfile = "3"
rcgen = "0.11"

[features]
default = ["rustls-native-roots", "tests-real-internet4", "penguin-binary"]
# Note that it does not make sense to use more than one TLS implementations
# at the same time, but there must be at least one if `penguin-binary` is
# enabled.
rustls-webpki-roots = ["webpki-roots", "tokio-tungstenite/rustls-tls-webpki-roots", "hyper-rustls/webpki-tokio", "__rustls"]
rustls-native-roots = ["rustls-native-certs", "tokio-tungstenite/rustls-tls-native-roots", "hyper-rustls/native-tokio", "__rustls"]
__rustls = ["rustls", "rustls-pemfile", "hyper-rustls", "tokio-rustls"]
nativetls = ["native-tls", "tokio-native-tls", "hyper-tls", "tokio-tungstenite/native-tls"]
# Allow some tests that require real internet connection
tests-real-internet4 = []
tests-real-internet6 = []
# Set the default localhost or unspecified address to IPv6
default-is-ipv6 = []
# Enabling this causes `penguin` to listen for `tokio-console` connections
tokio-console = ["console-subscriber"]
# `parking_lot`'s deadlock detection in a separate thread
deadlock-detection = ["parking_lot/deadlock_detection"]
# `penguin` binary
penguin-binary = [
    "arc-swap",
    "base64",
    "clap",
    "hyper",
    "once_cell",
    "sha1",
    "tracing-subscriber",
    "tokio/fs", "tokio/io-std", "tokio/net", "tokio/rt-multi-thread", "tokio/signal",
    "tokio-tungstenite/default",
]

[profile.release]
debug = true
