[package]
name = "penguin-rs"
version = "0.1.0"
authors = ["Zhang Maiyun <me@myzhangll.xyz>"]
edition = "2021"
description = "A fast TCP/UDP tunnel, transported over HTTP WebSockets"
readme = "README.md"
repository = "https://github.com/myzhang1029/penguin-rs"
license = "Apache-2.0 OR GPL-3.0-or-later"
keywords = ["cli", "web", "websocket"]
categories = ["asynchronous", "command-line-utilities", "network-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["cargo", "derive"] }
env_logger = "0.10"
futures-channel = "0.3"
futures-util = { version = "0.3", default-features = false }
http = "0.2"
log = "0.4"
rustls = "0.20"
rustls-native-certs = "0.6"
rustls-pemfile = "1"
thiserror = "1"
tokio = { version = "1", features = ["io-std", "macros", "rt-multi-thread"] }
tokio-stream-multiplexor = "0.5"
tokio-tungstenite = { version = "0.18", features = ["rustls-tls-native-roots"] }
tungstenite = { version = "0.18", features = ["rustls-tls-native-roots"] }
url = "2"
warp-reverse-proxy = { version = "1", features = ["rustls-tls"], default-features = false }
warp = { version = "0.3", features = ["tls"] }
webpki = "0.22"
