[package]
name = "rusty-penguin"
version = "0.5.1"
authors = ["Zhang Maiyun <me@myzhangll.xyz>"]
edition = "2021"
description = "A fast TCP/UDP tunnel, transported over HTTP WebSocket"
readme = "README.md"
repository = "https://github.com/myzhang1029/penguin-rs"
license = "Apache-2.0 OR GPL-3.0-or-later"
keywords = ["cli", "web", "websocket"]
categories = ["asynchronous", "command-line-utilities", "network-programming"]

[[bin]]
name = "penguin"
path = "src/main.rs"

[lib]
name = "penguin_mux"
path = "src/mux/lib.rs"

[dependencies]
arc-swap = "1"
base64 = "0.21"
bytes = "1"
clap = { version = "4", features = ["cargo", "derive"] }
console-subscriber = { version = "0.1", optional = true }
futures-util = { version = "0.3", default-features = false }
http = "0.2"
hyper = { version = ">=0.14.10", features = ["client", "server", "http1", "http2"] }
hyper-rustls = { version = "0.23", features = ["http1", "http2"], optional = true }
hyper-tls = { version = "0.5", optional = true }
native-tls = { version = "0.2", optional = true }
once_cell = "1"
parking_lot = "0.12"
rand = "0.8"
rustls = { version = "0.20", optional = true, features = ["dangerous_configuration"] }
rustls-native-certs = { version = "0.6", optional = true }
rustls-pemfile = { version = "1", optional = true }
sha1 = "0.10"
thiserror = "1"
tokio = { version = ">=1.23.1", features = ["fs", "io-std", "macros", "net", "rt-multi-thread", "signal", "sync"] }
tokio-native-tls = { version = "0.3", optional = true }
tokio-rustls = { version = "0.23", optional = true }
tokio-tungstenite = "0.18"
tracing = "0.1"
tracing-subscriber = "0.3"
tungstenite = "0.18"
webpki = { version = "0.22", optional = true }
webpki-roots = { version = "0.22", optional = true }

[dev-dependencies]
ctor = "0.1"
tempfile = "3"
rcgen = "0.10"

[features]
default = ["rustls-native-roots", "tests-real-internet4"]
# Note that it does not make sense to use more than one TLS implementations
# at the same time, but there must be at least one.
rustls-webpki-roots = ["webpki-roots", "tokio-tungstenite/rustls-tls-webpki-roots", "tungstenite/rustls-tls-webpki-roots", "hyper-rustls/webpki-tokio", "__rustls"]
rustls-native-roots = ["rustls-native-certs", "tokio-tungstenite/rustls-tls-native-roots", "tungstenite/rustls-tls-native-roots", "hyper-rustls/native-tokio", "__rustls"]
__rustls = ["rustls", "rustls-pemfile", "hyper-rustls", "tokio-rustls", "webpki"]
nativetls = ["native-tls", "tokio-native-tls", "hyper-tls", "tokio-tungstenite/native-tls", "tungstenite/native-tls"]
# Allows some tests that require real internet connection
tests-real-internet4 = []
tests-real-internet6 = []
tokio-console = ["console-subscriber"]
deadlock_detection = ["parking_lot/deadlock_detection"]

[profile.release]
debug = true
