name: Build macOS Releases

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build macOS Releases
    runs-on: macos-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2

    - name: Install Rust with aarch64 toolchain
      run:
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --target aarch64-apple-darwin,x86_64-apple-darwin

    - name: Build release
      run: |
        cargo build --release --target x86_64-apple-darwin
        cargo build --release --target aarch64-apple-darwin

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        path: target/*/release/penguin
